Add MIRAX fixture
bayer-science-for-a-better-life/tiffslide pull request #54
Opened 2023-01-05 16:53 UTC by GuillaumeDesforges

The MIRAX fixture marks test with the "mirax" marker. By default all MIRAX tests are skipped. To enable a MIRAX test, add a "support_mirax" marker to a test.

2023-01-06 15:03 UTC, ap-- requested changes
Please configure pyproject.toml to not run the mirax tests by default.

```toml
# pyproject.toml
[tool.pytest.ini_options]
addopts = [
  "-v",
  # (only needed by windows) disable faulthandler plugin to suppress non-fatal error msgs
  "-p", "no:faulthandler",
  "-m", "not compat",
  "-m", "not mirax",
  "--strict-markers"
]
markers = [
  "mirax",
  "support_mirax",
  "compat",
]
```

2023-01-06 15:03 UTC, ap-- commented
Hi Guillaume,

I'm a bit worried about the ~500Mb download that would happen by default when running the test suite.

Could you configure pytest to skip mirax tests by default and require to explicitly provide the mirax marker to run the supported tests? `pytest -m mirax`

We would then run the mirax tests locally for now and not in the CI and come up with a good solution for loading `CMU-1.zip` for CI tests.

There's other places where we could load it from if we need more frequent mirax testing (i.e. https://gist.github.com/ap--/4143a86a73b83f717555cb88aa2dd96e). I'd almost prefer if we could just generate our own minimal mirax file or find one with the right license and a size `<= 10Mb` or so...

Cheers,
Andreas 😃

2023-04-13 15:41 UTC, GuillaumeDesforges commented
Sorry, I am not working on MIRAX anymore and have had to put that on the side for the time being :disappointed: I'll get back to it when I get some time, but I can't garantee I ever will...

2023-04-15 18:54 UTC, ap-- commented
No worries 😃 
Thanks for the update.

I'll close this PR then for now. If at any future point in time you might revisit feel free to reopen.

Also, in case you have any insights or details about problems you ran into, it would be awesome if you could add that information to #44 

Cheers,
Andreas 😊

2023-04-15 18:54 UTC, closed without merging